### ISSUE TITLE
Cannot compile on Debian/jessie and /wheezy systems (0.11)

### ISSUE THREAD

**Issue by eserte** [benkasminbullock/json-create#35]
gcc48 does not exist here:

```
gcc48 -c   -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"0.11\" -DXS_VERSION=\"0.11\" -fPIC "-I/opt/perl-5.10.1/lib/5.10.1/x86_64-linux/CORE"   Create.c
/bin/sh: 1: gcc48: not found
```

**Comment by benkasminbullock** [comment]
Thanks for pointing this out, I have uploaded a new version.

**Comment by benkasminbullock** [comment]
This version on CPAN should be OK:

https://metacpan.org/release/BKB/JSON-Create-0.12

Was also missing benchmarking code. I found some errors in the string handlers when benchmarking and was too anxious to release a new version.

If this doesn't fix the issue, please feel free to reopen. Thanks again.
