### ISSUE TITLE
Justification?

### ISSUE THREAD

**Issue by haarg** [benkasminbullock/json-create#4]
It isn't obvious why this module exists, since there are several existing solutions for JSON serialization on CPAN.  It would be good to add something to the docs to show why someone should (or shouldn't) choose this module over any of the more established competing modules.

**Comment by zoffixznet** [comment]
:+1: it definitely would be very helpful.

**Comment by benkasminbullock** [comment]
Thank you for reporting your concerns.

However, a careful perusal of the documentation will reveal that it does say (on around the first line) that it's currently in very early testing stages.

The work I have done in getting to 0.01 is to get it to compile on the majority of CPAN testers machines:

http://matrix.cpantesters.org/?dist=JSON-Create%200.00_01
http://matrix.cpantesters.org/?dist=JSON-Create%200.00_02
http://matrix.cpantesters.org/?dist=JSON-Create%200.00_03
http://matrix.cpantesters.org/?dist=JSON-Create+0.00_04

The documentation also discusses why I wrote this, so with apologies I am closing this issue.
