### ISSUE TITLE
Unescaped left brace in regex is illegal in regex

### ISSUE THREAD

**Issue by eserte** [benkasminbullock/json-create#41]
t/json-create.t fails with perl 5.25.x:

```
Unescaped left brace in regex is illegal in regex; marked by <-- HERE in m/"a":{ <-- HERE "b":"c"}/ at t/json-create.t line 18.
t/json-create.t ... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by benkasminbullock** [comment]
Thanks for this report.

I have a testing version which fixes this issue:

http://matrix.cpantesters.org/?dist=JSON-Create+0.20_01

It looks like it is OK so I will release that soon.

Best

Ben Bullock

**Comment by benkasminbullock** [comment]
I think it's OK now:

http://fast-matrix.cpantesters.org/?dist=JSON-Create%200.21
