### ISSUE TITLE
Links to examples don't work anymore (api.metacpan.org/v0 is gone)

### ISSUE THREAD

**Issue by eserte** [benkasminbullock/json-create#43]
For example, the link to examples/synopsis.pl in https://metacpan.org/pod/release/BKB/JSON-Create-0.22/lib/JSON/Create.pm#SYNOPSIS does not work anymore: https://api.metacpan.org/source/BKB/JSON-Create-0.22/examples/synopsis.pl shows the message:
```
MetaCPAN v0 API has been has been shut down!

See the MetaCPAN v1 API should be used instead. 
```

**Comment by benkasminbullock** [comment]
Thanks for this bug report. I have released a new version of JSON::Create
which should address this issue. I'll be updating the other modules
affected by this individually. I've also updated the module
JSON::Create::PP with this release.
